name: iOS Starter Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Release Scheme
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.0.11
      with: 
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
